// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rectangles.Data;

#nullable disable

namespace Rectangles.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230526022544_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rectangle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("X1")
                        .HasColumnType("int");

                    b.Property<int>("X2")
                        .HasColumnType("int");

                    b.Property<int>("Y1")
                        .HasColumnType("int");

                    b.Property<int>("Y2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rectangles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            X1 = 0,
                            X2 = 5,
                            Y1 = 0,
                            Y2 = 5
                        },
                        new
                        {
                            Id = 2,
                            X1 = 10,
                            X2 = 15,
                            Y1 = 10,
                            Y2 = 15
                        },
                        new
                        {
                            Id = 3,
                            X1 = 20,
                            X2 = 25,
                            Y1 = 20,
                            Y2 = 25
                        },
                        new
                        {
                            Id = 4,
                            X1 = 30,
                            X2 = 35,
                            Y1 = 30,
                            Y2 = 35
                        },
                        new
                        {
                            Id = 5,
                            X1 = 40,
                            X2 = 45,
                            Y1 = 40,
                            Y2 = 45
                        },
                        new
                        {
                            Id = 6,
                            X1 = 50,
                            X2 = 55,
                            Y1 = 50,
                            Y2 = 55
                        },
                        new
                        {
                            Id = 7,
                            X1 = 60,
                            X2 = 65,
                            Y1 = 60,
                            Y2 = 65
                        },
                        new
                        {
                            Id = 8,
                            X1 = 70,
                            X2 = 75,
                            Y1 = 70,
                            Y2 = 75
                        },
                        new
                        {
                            Id = 9,
                            X1 = 80,
                            X2 = 85,
                            Y1 = 80,
                            Y2 = 85
                        },
                        new
                        {
                            Id = 10,
                            X1 = 90,
                            X2 = 95,
                            Y1 = 90,
                            Y2 = 95
                        },
                        new
                        {
                            Id = 11,
                            X1 = 100,
                            X2 = 105,
                            Y1 = 100,
                            Y2 = 105
                        },
                        new
                        {
                            Id = 12,
                            X1 = 110,
                            X2 = 115,
                            Y1 = 110,
                            Y2 = 115
                        },
                        new
                        {
                            Id = 13,
                            X1 = 120,
                            X2 = 125,
                            Y1 = 120,
                            Y2 = 125
                        },
                        new
                        {
                            Id = 14,
                            X1 = 130,
                            X2 = 135,
                            Y1 = 130,
                            Y2 = 135
                        },
                        new
                        {
                            Id = 15,
                            X1 = 140,
                            X2 = 145,
                            Y1 = 140,
                            Y2 = 145
                        },
                        new
                        {
                            Id = 16,
                            X1 = 150,
                            X2 = 155,
                            Y1 = 150,
                            Y2 = 155
                        },
                        new
                        {
                            Id = 17,
                            X1 = 160,
                            X2 = 165,
                            Y1 = 160,
                            Y2 = 165
                        },
                        new
                        {
                            Id = 18,
                            X1 = 170,
                            X2 = 175,
                            Y1 = 170,
                            Y2 = 175
                        },
                        new
                        {
                            Id = 19,
                            X1 = 180,
                            X2 = 185,
                            Y1 = 180,
                            Y2 = 185
                        },
                        new
                        {
                            Id = 20,
                            X1 = 190,
                            X2 = 195,
                            Y1 = 190,
                            Y2 = 195
                        },
                        new
                        {
                            Id = 21,
                            X1 = 200,
                            X2 = 205,
                            Y1 = 200,
                            Y2 = 205
                        },
                        new
                        {
                            Id = 22,
                            X1 = 210,
                            X2 = 215,
                            Y1 = 210,
                            Y2 = 215
                        },
                        new
                        {
                            Id = 23,
                            X1 = 220,
                            X2 = 225,
                            Y1 = 220,
                            Y2 = 225
                        },
                        new
                        {
                            Id = 24,
                            X1 = 230,
                            X2 = 235,
                            Y1 = 230,
                            Y2 = 235
                        },
                        new
                        {
                            Id = 25,
                            X1 = 240,
                            X2 = 245,
                            Y1 = 240,
                            Y2 = 245
                        },
                        new
                        {
                            Id = 26,
                            X1 = 250,
                            X2 = 255,
                            Y1 = 250,
                            Y2 = 255
                        },
                        new
                        {
                            Id = 27,
                            X1 = 260,
                            X2 = 265,
                            Y1 = 260,
                            Y2 = 265
                        },
                        new
                        {
                            Id = 28,
                            X1 = 270,
                            X2 = 275,
                            Y1 = 270,
                            Y2 = 275
                        },
                        new
                        {
                            Id = 29,
                            X1 = 280,
                            X2 = 285,
                            Y1 = 280,
                            Y2 = 285
                        },
                        new
                        {
                            Id = 30,
                            X1 = 290,
                            X2 = 295,
                            Y1 = 290,
                            Y2 = 295
                        },
                        new
                        {
                            Id = 31,
                            X1 = 300,
                            X2 = 305,
                            Y1 = 300,
                            Y2 = 305
                        },
                        new
                        {
                            Id = 32,
                            X1 = 310,
                            X2 = 315,
                            Y1 = 310,
                            Y2 = 315
                        },
                        new
                        {
                            Id = 33,
                            X1 = 320,
                            X2 = 325,
                            Y1 = 320,
                            Y2 = 325
                        },
                        new
                        {
                            Id = 34,
                            X1 = 330,
                            X2 = 335,
                            Y1 = 330,
                            Y2 = 335
                        },
                        new
                        {
                            Id = 35,
                            X1 = 340,
                            X2 = 345,
                            Y1 = 340,
                            Y2 = 345
                        },
                        new
                        {
                            Id = 36,
                            X1 = 350,
                            X2 = 355,
                            Y1 = 350,
                            Y2 = 355
                        },
                        new
                        {
                            Id = 37,
                            X1 = 360,
                            X2 = 365,
                            Y1 = 360,
                            Y2 = 365
                        },
                        new
                        {
                            Id = 38,
                            X1 = 370,
                            X2 = 375,
                            Y1 = 370,
                            Y2 = 375
                        },
                        new
                        {
                            Id = 39,
                            X1 = 380,
                            X2 = 385,
                            Y1 = 380,
                            Y2 = 385
                        },
                        new
                        {
                            Id = 40,
                            X1 = 390,
                            X2 = 395,
                            Y1 = 390,
                            Y2 = 395
                        },
                        new
                        {
                            Id = 41,
                            X1 = 400,
                            X2 = 405,
                            Y1 = 400,
                            Y2 = 405
                        },
                        new
                        {
                            Id = 42,
                            X1 = 410,
                            X2 = 415,
                            Y1 = 410,
                            Y2 = 415
                        },
                        new
                        {
                            Id = 43,
                            X1 = 420,
                            X2 = 425,
                            Y1 = 420,
                            Y2 = 425
                        },
                        new
                        {
                            Id = 44,
                            X1 = 430,
                            X2 = 435,
                            Y1 = 430,
                            Y2 = 435
                        },
                        new
                        {
                            Id = 45,
                            X1 = 440,
                            X2 = 445,
                            Y1 = 440,
                            Y2 = 445
                        },
                        new
                        {
                            Id = 46,
                            X1 = 450,
                            X2 = 455,
                            Y1 = 450,
                            Y2 = 455
                        },
                        new
                        {
                            Id = 47,
                            X1 = 460,
                            X2 = 465,
                            Y1 = 460,
                            Y2 = 465
                        },
                        new
                        {
                            Id = 48,
                            X1 = 470,
                            X2 = 475,
                            Y1 = 470,
                            Y2 = 475
                        },
                        new
                        {
                            Id = 49,
                            X1 = 480,
                            X2 = 485,
                            Y1 = 480,
                            Y2 = 485
                        },
                        new
                        {
                            Id = 50,
                            X1 = 490,
                            X2 = 495,
                            Y1 = 490,
                            Y2 = 495
                        },
                        new
                        {
                            Id = 51,
                            X1 = 500,
                            X2 = 505,
                            Y1 = 500,
                            Y2 = 505
                        },
                        new
                        {
                            Id = 52,
                            X1 = 510,
                            X2 = 515,
                            Y1 = 510,
                            Y2 = 515
                        },
                        new
                        {
                            Id = 53,
                            X1 = 520,
                            X2 = 525,
                            Y1 = 520,
                            Y2 = 525
                        },
                        new
                        {
                            Id = 54,
                            X1 = 530,
                            X2 = 535,
                            Y1 = 530,
                            Y2 = 535
                        },
                        new
                        {
                            Id = 55,
                            X1 = 540,
                            X2 = 545,
                            Y1 = 540,
                            Y2 = 545
                        },
                        new
                        {
                            Id = 56,
                            X1 = 550,
                            X2 = 555,
                            Y1 = 550,
                            Y2 = 555
                        },
                        new
                        {
                            Id = 57,
                            X1 = 560,
                            X2 = 565,
                            Y1 = 560,
                            Y2 = 565
                        },
                        new
                        {
                            Id = 58,
                            X1 = 570,
                            X2 = 575,
                            Y1 = 570,
                            Y2 = 575
                        },
                        new
                        {
                            Id = 59,
                            X1 = 580,
                            X2 = 585,
                            Y1 = 580,
                            Y2 = 585
                        },
                        new
                        {
                            Id = 60,
                            X1 = 590,
                            X2 = 595,
                            Y1 = 590,
                            Y2 = 595
                        },
                        new
                        {
                            Id = 61,
                            X1 = 600,
                            X2 = 605,
                            Y1 = 600,
                            Y2 = 605
                        },
                        new
                        {
                            Id = 62,
                            X1 = 610,
                            X2 = 615,
                            Y1 = 610,
                            Y2 = 615
                        },
                        new
                        {
                            Id = 63,
                            X1 = 620,
                            X2 = 625,
                            Y1 = 620,
                            Y2 = 625
                        },
                        new
                        {
                            Id = 64,
                            X1 = 630,
                            X2 = 635,
                            Y1 = 630,
                            Y2 = 635
                        },
                        new
                        {
                            Id = 65,
                            X1 = 640,
                            X2 = 645,
                            Y1 = 640,
                            Y2 = 645
                        },
                        new
                        {
                            Id = 66,
                            X1 = 650,
                            X2 = 655,
                            Y1 = 650,
                            Y2 = 655
                        },
                        new
                        {
                            Id = 67,
                            X1 = 660,
                            X2 = 665,
                            Y1 = 660,
                            Y2 = 665
                        },
                        new
                        {
                            Id = 68,
                            X1 = 670,
                            X2 = 675,
                            Y1 = 670,
                            Y2 = 675
                        },
                        new
                        {
                            Id = 69,
                            X1 = 680,
                            X2 = 685,
                            Y1 = 680,
                            Y2 = 685
                        },
                        new
                        {
                            Id = 70,
                            X1 = 690,
                            X2 = 695,
                            Y1 = 690,
                            Y2 = 695
                        },
                        new
                        {
                            Id = 71,
                            X1 = 700,
                            X2 = 705,
                            Y1 = 700,
                            Y2 = 705
                        },
                        new
                        {
                            Id = 72,
                            X1 = 710,
                            X2 = 715,
                            Y1 = 710,
                            Y2 = 715
                        },
                        new
                        {
                            Id = 73,
                            X1 = 720,
                            X2 = 725,
                            Y1 = 720,
                            Y2 = 725
                        },
                        new
                        {
                            Id = 74,
                            X1 = 730,
                            X2 = 735,
                            Y1 = 730,
                            Y2 = 735
                        },
                        new
                        {
                            Id = 75,
                            X1 = 740,
                            X2 = 745,
                            Y1 = 740,
                            Y2 = 745
                        },
                        new
                        {
                            Id = 76,
                            X1 = 750,
                            X2 = 755,
                            Y1 = 750,
                            Y2 = 755
                        },
                        new
                        {
                            Id = 77,
                            X1 = 760,
                            X2 = 765,
                            Y1 = 760,
                            Y2 = 765
                        },
                        new
                        {
                            Id = 78,
                            X1 = 770,
                            X2 = 775,
                            Y1 = 770,
                            Y2 = 775
                        },
                        new
                        {
                            Id = 79,
                            X1 = 780,
                            X2 = 785,
                            Y1 = 780,
                            Y2 = 785
                        },
                        new
                        {
                            Id = 80,
                            X1 = 790,
                            X2 = 795,
                            Y1 = 790,
                            Y2 = 795
                        },
                        new
                        {
                            Id = 81,
                            X1 = 800,
                            X2 = 805,
                            Y1 = 800,
                            Y2 = 805
                        },
                        new
                        {
                            Id = 82,
                            X1 = 810,
                            X2 = 815,
                            Y1 = 810,
                            Y2 = 815
                        },
                        new
                        {
                            Id = 83,
                            X1 = 820,
                            X2 = 825,
                            Y1 = 820,
                            Y2 = 825
                        },
                        new
                        {
                            Id = 84,
                            X1 = 830,
                            X2 = 835,
                            Y1 = 830,
                            Y2 = 835
                        },
                        new
                        {
                            Id = 85,
                            X1 = 840,
                            X2 = 845,
                            Y1 = 840,
                            Y2 = 845
                        },
                        new
                        {
                            Id = 86,
                            X1 = 850,
                            X2 = 855,
                            Y1 = 850,
                            Y2 = 855
                        },
                        new
                        {
                            Id = 87,
                            X1 = 860,
                            X2 = 865,
                            Y1 = 860,
                            Y2 = 865
                        },
                        new
                        {
                            Id = 88,
                            X1 = 870,
                            X2 = 875,
                            Y1 = 870,
                            Y2 = 875
                        },
                        new
                        {
                            Id = 89,
                            X1 = 880,
                            X2 = 885,
                            Y1 = 880,
                            Y2 = 885
                        },
                        new
                        {
                            Id = 90,
                            X1 = 890,
                            X2 = 895,
                            Y1 = 890,
                            Y2 = 895
                        },
                        new
                        {
                            Id = 91,
                            X1 = 900,
                            X2 = 905,
                            Y1 = 900,
                            Y2 = 905
                        },
                        new
                        {
                            Id = 92,
                            X1 = 910,
                            X2 = 915,
                            Y1 = 910,
                            Y2 = 915
                        },
                        new
                        {
                            Id = 93,
                            X1 = 920,
                            X2 = 925,
                            Y1 = 920,
                            Y2 = 925
                        },
                        new
                        {
                            Id = 94,
                            X1 = 930,
                            X2 = 935,
                            Y1 = 930,
                            Y2 = 935
                        },
                        new
                        {
                            Id = 95,
                            X1 = 940,
                            X2 = 945,
                            Y1 = 940,
                            Y2 = 945
                        },
                        new
                        {
                            Id = 96,
                            X1 = 950,
                            X2 = 955,
                            Y1 = 950,
                            Y2 = 955
                        },
                        new
                        {
                            Id = 97,
                            X1 = 960,
                            X2 = 965,
                            Y1 = 960,
                            Y2 = 965
                        },
                        new
                        {
                            Id = 98,
                            X1 = 970,
                            X2 = 975,
                            Y1 = 970,
                            Y2 = 975
                        },
                        new
                        {
                            Id = 99,
                            X1 = 980,
                            X2 = 985,
                            Y1 = 980,
                            Y2 = 985
                        },
                        new
                        {
                            Id = 100,
                            X1 = 990,
                            X2 = 995,
                            Y1 = 990,
                            Y2 = 995
                        },
                        new
                        {
                            Id = 101,
                            X1 = 0,
                            X2 = 6,
                            Y1 = 0,
                            Y2 = 6
                        },
                        new
                        {
                            Id = 102,
                            X1 = 10,
                            X2 = 16,
                            Y1 = 10,
                            Y2 = 16
                        },
                        new
                        {
                            Id = 103,
                            X1 = 20,
                            X2 = 26,
                            Y1 = 20,
                            Y2 = 26
                        },
                        new
                        {
                            Id = 104,
                            X1 = 30,
                            X2 = 36,
                            Y1 = 30,
                            Y2 = 36
                        },
                        new
                        {
                            Id = 105,
                            X1 = 40,
                            X2 = 46,
                            Y1 = 40,
                            Y2 = 46
                        },
                        new
                        {
                            Id = 106,
                            X1 = 50,
                            X2 = 56,
                            Y1 = 50,
                            Y2 = 56
                        },
                        new
                        {
                            Id = 107,
                            X1 = 60,
                            X2 = 66,
                            Y1 = 60,
                            Y2 = 66
                        },
                        new
                        {
                            Id = 108,
                            X1 = 70,
                            X2 = 76,
                            Y1 = 70,
                            Y2 = 76
                        },
                        new
                        {
                            Id = 109,
                            X1 = 80,
                            X2 = 86,
                            Y1 = 80,
                            Y2 = 86
                        },
                        new
                        {
                            Id = 110,
                            X1 = 90,
                            X2 = 96,
                            Y1 = 90,
                            Y2 = 96
                        },
                        new
                        {
                            Id = 111,
                            X1 = 100,
                            X2 = 106,
                            Y1 = 100,
                            Y2 = 106
                        },
                        new
                        {
                            Id = 112,
                            X1 = 110,
                            X2 = 116,
                            Y1 = 110,
                            Y2 = 116
                        },
                        new
                        {
                            Id = 113,
                            X1 = 120,
                            X2 = 126,
                            Y1 = 120,
                            Y2 = 126
                        },
                        new
                        {
                            Id = 114,
                            X1 = 130,
                            X2 = 136,
                            Y1 = 130,
                            Y2 = 136
                        },
                        new
                        {
                            Id = 115,
                            X1 = 140,
                            X2 = 146,
                            Y1 = 140,
                            Y2 = 146
                        },
                        new
                        {
                            Id = 116,
                            X1 = 150,
                            X2 = 156,
                            Y1 = 150,
                            Y2 = 156
                        },
                        new
                        {
                            Id = 117,
                            X1 = 160,
                            X2 = 166,
                            Y1 = 160,
                            Y2 = 166
                        },
                        new
                        {
                            Id = 118,
                            X1 = 170,
                            X2 = 176,
                            Y1 = 170,
                            Y2 = 176
                        },
                        new
                        {
                            Id = 119,
                            X1 = 180,
                            X2 = 186,
                            Y1 = 180,
                            Y2 = 186
                        },
                        new
                        {
                            Id = 120,
                            X1 = 190,
                            X2 = 196,
                            Y1 = 190,
                            Y2 = 196
                        },
                        new
                        {
                            Id = 121,
                            X1 = 200,
                            X2 = 206,
                            Y1 = 200,
                            Y2 = 206
                        },
                        new
                        {
                            Id = 122,
                            X1 = 210,
                            X2 = 216,
                            Y1 = 210,
                            Y2 = 216
                        },
                        new
                        {
                            Id = 123,
                            X1 = 220,
                            X2 = 226,
                            Y1 = 220,
                            Y2 = 226
                        },
                        new
                        {
                            Id = 124,
                            X1 = 230,
                            X2 = 236,
                            Y1 = 230,
                            Y2 = 236
                        },
                        new
                        {
                            Id = 125,
                            X1 = 240,
                            X2 = 246,
                            Y1 = 240,
                            Y2 = 246
                        },
                        new
                        {
                            Id = 126,
                            X1 = 250,
                            X2 = 256,
                            Y1 = 250,
                            Y2 = 256
                        },
                        new
                        {
                            Id = 127,
                            X1 = 260,
                            X2 = 266,
                            Y1 = 260,
                            Y2 = 266
                        },
                        new
                        {
                            Id = 128,
                            X1 = 270,
                            X2 = 276,
                            Y1 = 270,
                            Y2 = 276
                        },
                        new
                        {
                            Id = 129,
                            X1 = 280,
                            X2 = 286,
                            Y1 = 280,
                            Y2 = 286
                        },
                        new
                        {
                            Id = 130,
                            X1 = 290,
                            X2 = 296,
                            Y1 = 290,
                            Y2 = 296
                        },
                        new
                        {
                            Id = 131,
                            X1 = 300,
                            X2 = 306,
                            Y1 = 300,
                            Y2 = 306
                        },
                        new
                        {
                            Id = 132,
                            X1 = 310,
                            X2 = 316,
                            Y1 = 310,
                            Y2 = 316
                        },
                        new
                        {
                            Id = 133,
                            X1 = 320,
                            X2 = 326,
                            Y1 = 320,
                            Y2 = 326
                        },
                        new
                        {
                            Id = 134,
                            X1 = 330,
                            X2 = 336,
                            Y1 = 330,
                            Y2 = 336
                        },
                        new
                        {
                            Id = 135,
                            X1 = 340,
                            X2 = 346,
                            Y1 = 340,
                            Y2 = 346
                        },
                        new
                        {
                            Id = 136,
                            X1 = 350,
                            X2 = 356,
                            Y1 = 350,
                            Y2 = 356
                        },
                        new
                        {
                            Id = 137,
                            X1 = 360,
                            X2 = 366,
                            Y1 = 360,
                            Y2 = 366
                        },
                        new
                        {
                            Id = 138,
                            X1 = 370,
                            X2 = 376,
                            Y1 = 370,
                            Y2 = 376
                        },
                        new
                        {
                            Id = 139,
                            X1 = 380,
                            X2 = 386,
                            Y1 = 380,
                            Y2 = 386
                        },
                        new
                        {
                            Id = 140,
                            X1 = 390,
                            X2 = 396,
                            Y1 = 390,
                            Y2 = 396
                        },
                        new
                        {
                            Id = 141,
                            X1 = 400,
                            X2 = 406,
                            Y1 = 400,
                            Y2 = 406
                        },
                        new
                        {
                            Id = 142,
                            X1 = 410,
                            X2 = 416,
                            Y1 = 410,
                            Y2 = 416
                        },
                        new
                        {
                            Id = 143,
                            X1 = 420,
                            X2 = 426,
                            Y1 = 420,
                            Y2 = 426
                        },
                        new
                        {
                            Id = 144,
                            X1 = 430,
                            X2 = 436,
                            Y1 = 430,
                            Y2 = 436
                        },
                        new
                        {
                            Id = 145,
                            X1 = 440,
                            X2 = 446,
                            Y1 = 440,
                            Y2 = 446
                        },
                        new
                        {
                            Id = 146,
                            X1 = 450,
                            X2 = 456,
                            Y1 = 450,
                            Y2 = 456
                        },
                        new
                        {
                            Id = 147,
                            X1 = 460,
                            X2 = 466,
                            Y1 = 460,
                            Y2 = 466
                        },
                        new
                        {
                            Id = 148,
                            X1 = 470,
                            X2 = 476,
                            Y1 = 470,
                            Y2 = 476
                        },
                        new
                        {
                            Id = 149,
                            X1 = 480,
                            X2 = 486,
                            Y1 = 480,
                            Y2 = 486
                        },
                        new
                        {
                            Id = 150,
                            X1 = 490,
                            X2 = 496,
                            Y1 = 490,
                            Y2 = 496
                        },
                        new
                        {
                            Id = 151,
                            X1 = 500,
                            X2 = 506,
                            Y1 = 500,
                            Y2 = 506
                        },
                        new
                        {
                            Id = 152,
                            X1 = 510,
                            X2 = 516,
                            Y1 = 510,
                            Y2 = 516
                        },
                        new
                        {
                            Id = 153,
                            X1 = 520,
                            X2 = 526,
                            Y1 = 520,
                            Y2 = 526
                        },
                        new
                        {
                            Id = 154,
                            X1 = 530,
                            X2 = 536,
                            Y1 = 530,
                            Y2 = 536
                        },
                        new
                        {
                            Id = 155,
                            X1 = 540,
                            X2 = 546,
                            Y1 = 540,
                            Y2 = 546
                        },
                        new
                        {
                            Id = 156,
                            X1 = 550,
                            X2 = 556,
                            Y1 = 550,
                            Y2 = 556
                        },
                        new
                        {
                            Id = 157,
                            X1 = 560,
                            X2 = 566,
                            Y1 = 560,
                            Y2 = 566
                        },
                        new
                        {
                            Id = 158,
                            X1 = 570,
                            X2 = 576,
                            Y1 = 570,
                            Y2 = 576
                        },
                        new
                        {
                            Id = 159,
                            X1 = 580,
                            X2 = 586,
                            Y1 = 580,
                            Y2 = 586
                        },
                        new
                        {
                            Id = 160,
                            X1 = 590,
                            X2 = 596,
                            Y1 = 590,
                            Y2 = 596
                        },
                        new
                        {
                            Id = 161,
                            X1 = 600,
                            X2 = 606,
                            Y1 = 600,
                            Y2 = 606
                        },
                        new
                        {
                            Id = 162,
                            X1 = 610,
                            X2 = 616,
                            Y1 = 610,
                            Y2 = 616
                        },
                        new
                        {
                            Id = 163,
                            X1 = 620,
                            X2 = 626,
                            Y1 = 620,
                            Y2 = 626
                        },
                        new
                        {
                            Id = 164,
                            X1 = 630,
                            X2 = 636,
                            Y1 = 630,
                            Y2 = 636
                        },
                        new
                        {
                            Id = 165,
                            X1 = 640,
                            X2 = 646,
                            Y1 = 640,
                            Y2 = 646
                        },
                        new
                        {
                            Id = 166,
                            X1 = 650,
                            X2 = 656,
                            Y1 = 650,
                            Y2 = 656
                        },
                        new
                        {
                            Id = 167,
                            X1 = 660,
                            X2 = 666,
                            Y1 = 660,
                            Y2 = 666
                        },
                        new
                        {
                            Id = 168,
                            X1 = 670,
                            X2 = 676,
                            Y1 = 670,
                            Y2 = 676
                        },
                        new
                        {
                            Id = 169,
                            X1 = 680,
                            X2 = 686,
                            Y1 = 680,
                            Y2 = 686
                        },
                        new
                        {
                            Id = 170,
                            X1 = 690,
                            X2 = 696,
                            Y1 = 690,
                            Y2 = 696
                        },
                        new
                        {
                            Id = 171,
                            X1 = 700,
                            X2 = 706,
                            Y1 = 700,
                            Y2 = 706
                        },
                        new
                        {
                            Id = 172,
                            X1 = 710,
                            X2 = 716,
                            Y1 = 710,
                            Y2 = 716
                        },
                        new
                        {
                            Id = 173,
                            X1 = 720,
                            X2 = 726,
                            Y1 = 720,
                            Y2 = 726
                        },
                        new
                        {
                            Id = 174,
                            X1 = 730,
                            X2 = 736,
                            Y1 = 730,
                            Y2 = 736
                        },
                        new
                        {
                            Id = 175,
                            X1 = 740,
                            X2 = 746,
                            Y1 = 740,
                            Y2 = 746
                        },
                        new
                        {
                            Id = 176,
                            X1 = 750,
                            X2 = 756,
                            Y1 = 750,
                            Y2 = 756
                        },
                        new
                        {
                            Id = 177,
                            X1 = 760,
                            X2 = 766,
                            Y1 = 760,
                            Y2 = 766
                        },
                        new
                        {
                            Id = 178,
                            X1 = 770,
                            X2 = 776,
                            Y1 = 770,
                            Y2 = 776
                        },
                        new
                        {
                            Id = 179,
                            X1 = 780,
                            X2 = 786,
                            Y1 = 780,
                            Y2 = 786
                        },
                        new
                        {
                            Id = 180,
                            X1 = 790,
                            X2 = 796,
                            Y1 = 790,
                            Y2 = 796
                        },
                        new
                        {
                            Id = 181,
                            X1 = 800,
                            X2 = 806,
                            Y1 = 800,
                            Y2 = 806
                        },
                        new
                        {
                            Id = 182,
                            X1 = 810,
                            X2 = 816,
                            Y1 = 810,
                            Y2 = 816
                        },
                        new
                        {
                            Id = 183,
                            X1 = 820,
                            X2 = 826,
                            Y1 = 820,
                            Y2 = 826
                        },
                        new
                        {
                            Id = 184,
                            X1 = 830,
                            X2 = 836,
                            Y1 = 830,
                            Y2 = 836
                        },
                        new
                        {
                            Id = 185,
                            X1 = 840,
                            X2 = 846,
                            Y1 = 840,
                            Y2 = 846
                        },
                        new
                        {
                            Id = 186,
                            X1 = 850,
                            X2 = 856,
                            Y1 = 850,
                            Y2 = 856
                        },
                        new
                        {
                            Id = 187,
                            X1 = 860,
                            X2 = 866,
                            Y1 = 860,
                            Y2 = 866
                        },
                        new
                        {
                            Id = 188,
                            X1 = 870,
                            X2 = 876,
                            Y1 = 870,
                            Y2 = 876
                        },
                        new
                        {
                            Id = 189,
                            X1 = 880,
                            X2 = 886,
                            Y1 = 880,
                            Y2 = 886
                        },
                        new
                        {
                            Id = 190,
                            X1 = 890,
                            X2 = 896,
                            Y1 = 890,
                            Y2 = 896
                        },
                        new
                        {
                            Id = 191,
                            X1 = 900,
                            X2 = 906,
                            Y1 = 900,
                            Y2 = 906
                        },
                        new
                        {
                            Id = 192,
                            X1 = 910,
                            X2 = 916,
                            Y1 = 910,
                            Y2 = 916
                        },
                        new
                        {
                            Id = 193,
                            X1 = 920,
                            X2 = 926,
                            Y1 = 920,
                            Y2 = 926
                        },
                        new
                        {
                            Id = 194,
                            X1 = 930,
                            X2 = 936,
                            Y1 = 930,
                            Y2 = 936
                        },
                        new
                        {
                            Id = 195,
                            X1 = 940,
                            X2 = 946,
                            Y1 = 940,
                            Y2 = 946
                        },
                        new
                        {
                            Id = 196,
                            X1 = 950,
                            X2 = 956,
                            Y1 = 950,
                            Y2 = 956
                        },
                        new
                        {
                            Id = 197,
                            X1 = 960,
                            X2 = 966,
                            Y1 = 960,
                            Y2 = 966
                        },
                        new
                        {
                            Id = 198,
                            X1 = 970,
                            X2 = 976,
                            Y1 = 970,
                            Y2 = 976
                        },
                        new
                        {
                            Id = 199,
                            X1 = 980,
                            X2 = 986,
                            Y1 = 980,
                            Y2 = 986
                        },
                        new
                        {
                            Id = 200,
                            X1 = 990,
                            X2 = 996,
                            Y1 = 990,
                            Y2 = 996
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
